### PR TITLE
add 3 sec timeout when requesting to MetaMask

### PR DESCRIPTION
**Pull request by chnejohnson**
- #117

### CODE REVIEW

**Comment by re2005** [comment]
Thanks @chnejohnson for the new commit, Let me try to reproduce the `Metakask` issue on the preview URL.
I'ill get back here.

Perhaps for now we can disable the timeout, or really make it optional.

**Comment by re2005** [comment]
@chnejohnson We may can move on with this PR. Perhaps the `connectTimeout` should only be used if users pass a `number` value, or else is not active ?

Thanks

**Comment by chnejohnson** [comment]
@re2005 Just force-push a new commit with an optional timeout settings, please help me take a look. Thanks

**Comment by re2005** [comment]
@chnejohnson this is all looking good, and contains a fix that I'm waiting for a while, to prevent errors when trying to update balance.

Ready to be merged and publish ?

**Comment by chnejohnson** [comment]
@re2005 Certainly!

**Pull request merged**
